// Show notification
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_SHOW_WARNING = 'NOTIFICATION_SHOW_WARNING';
export const NOTIFICATION_SHOW_DANGER = 'NOTIFICATION_SHOW_DANGER';
export const NOTIFICATION_SHOW_SUCCESS = 'NOTIFICATION_SHOW_SUCCESS';
export const NOTIFICATION_SHOW_INFO = 'NOTIFICATION_SHOW_INFO';

// Hide notification
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';

// Set value of the SearchField
export const SEARCH_FIELD_SET_TEXT = 'SEARCH_FIELD_SET_TEXT';

// Clear the SearchField
export const SEARCH_FIELD_CLEAR = 'SEARCH_FIELD_CLEAR';


export default {
  NOTIFICATION_SHOW,
  NOTIFICATION_SHOW_WARNING,
  NOTIFICATION_SHOW_DANGER,
  NOTIFICATION_SHOW_SUCCESS,
  NOTIFICATION_SHOW_INFO,
  NOTIFICATION_HIDE,

  SEARCH_FIELD_SET_TEXT,
  SEARCH_FIELD_CLEAR,
};
