// Show notification
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_SHOW_WARNING = 'NOTIFICATION_SHOW_WARNING';
export const NOTIFICATION_SHOW_DANGER = 'NOTIFICATION_SHOW_DANGER';
export const NOTIFICATION_SHOW_SUCCESS = 'NOTIFICATION_SHOW_SUCCESS';
export const NOTIFICATION_SHOW_INFO = 'NOTIFICATION_SHOW_INFO';

// Hide notification
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
export const NOTIFICATION_SET_TIMER = 'NOTIFICATION_SET_TIMER';


export default {
  NOTIFICATION_SHOW,
  NOTIFICATION_SHOW_WARNING,
  NOTIFICATION_SHOW_DANGER,
  NOTIFICATION_SHOW_SUCCESS,
  NOTIFICATION_SHOW_INFO,
  NOTIFICATION_HIDE,
  NOTIFICATION_SET_TIMER,
};
